[cnd]
    # Set debug mode
    debug = true
    # Is comunity
    community = true


[hunchly]
# path to hunchly location
    api_path = "C:\\Program Files (x86)\\Hunchly 2.4.3\\Dashboard\\HunchlyAPI.exe"

[whatsmynmeapp]
# link on whatsmynameapp site definitions
    data = "https://raw.githubusercontent.com/WebBreacher/WhatsMyName/main/wmn-data.json"

[db]
    type = 'tinydb'
    db_path= 'db/db.json'

[tavily]
    api_key = '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'